"""added user_id column in task table

Revision ID: 422a69f2758e
Revises: 
Create Date: 2026-07-26 17:21:23.739183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422a69f2758e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_column('user_tasks', 'user_id')
    # ### end Alembic commands ###
